server:
  port: 8080


dubbo:
  application:
      name: dubbo-service1
  registry:
      address: zookeeper://192.168.0.179:2181
  protocol:
      name: dubbo # 指定通信协议
      port: 20880 # 通信端口  这里指的是与消费者间的通信协议与端口
  provider:
      timeout: 10000 # 配置全局调用服务超时时间，dubbo默认是1s，肯定不够用呀
      retries: 3 # 重试3次
      delay: -1
  scan: com.yunhe.dubbo
  server: true



